export const metricTranslations = {
    Goals: 'Gols por jogo',
    Assists: 'Assistências por jogo',
    Acc_Passes_Percentage: 'Precisão de Passes (%)',
    Key_Passes_n: 'Passes Chave por jogo',
    Passes_Total_n: 'Passes Totais por jogo',
    Tackles: 'Desarmes por jogo',
    Blocks: 'Bloqueios por jogo',
    Interceptations: 'Interceptações por jogo',
    Duels_Won_Percentage: 'Duelos Ganhos (%)',
    Shots: 'Chutes por jogo',
    ShotsOnTarget_Percentage: 'Chutes no Alvo (%)',
    Goals_ShotsOnTarget: 'Gols por Chute ao Alvo por jogo',
    Dribbles_Attempts_n: 'Tentativas de Drible por jogo',
    Dribbles_Success_Percentage: 'Sucesso de Dribles (%)',
    Fouls_Draw_n: 'Faltas Sofridas',
    Fouls_Committed_n: 'Faltas Cometidas',
    Save_Percentage: 'Porcentagem de Defesas',
    Goals_Conceded_n: 'Gols Sofridos'
}